# Generated by Django 5.0.2 on 2024-03-06 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("department", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("introduction", models.CharField(max_length=200)),
                ("photo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("introduction", models.CharField(max_length=200)),
                ("photo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_lastmodified", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CTImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_id", models.CharField(max_length=20)),
                ("image_url", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.patient"
                    ),
                ),
            ],
        ),
    ]
