# Generated by Django 5.0.2 on 2024-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_niftiimage_alter_doctor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
    ]
