# Generated by Django 5.0.2 on 2024-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_alter_doctor_age_alter_patient_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.CharField(max_length=50, verbose_name="邮箱"),
        ),
    ]
