# Generated by Django 5.0.2 on 2024-03-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_alter_doctor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="ct_image_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="App.niftiimage",
                verbose_name="CT图像",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_photo", verbose_name="头像"
            ),
        ),
    ]
