# Generated by Django 5.0.2 on 2024-03-15 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0005_medicalrecord_ct_image_id_alter_doctor_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="ct_image_id",
            new_name="record_ct_image",
        ),
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="patient_id",
            new_name="record_patient",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="ct_image",
            new_name="patient_ct_image",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="medical_record",
            new_name="record",
        ),
    ]
